// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ŽVPAIS_API.Data;

#nullable disable

namespace ŽVPAIS_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323083219_MakeNotesNullable")]
    partial class MakeNotesNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ObjectMaterial", b =>
                {
                    b.Property<int>("ObjectId")
                        .HasColumnType("integer")
                        .HasColumnName("object_id");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer")
                        .HasColumnName("material_id");

                    b.Property<int>("IdObjectMaterial")
                        .HasColumnType("integer")
                        .HasColumnName("id_object_material");

                    b.Property<double?>("Mass")
                        .HasColumnType("double precision")
                        .HasColumnName("mass");

                    b.Property<double?>("Percentage")
                        .HasColumnType("double precision")
                        .HasColumnName("percentage");

                    b.Property<double?>("Volume")
                        .HasColumnType("double precision")
                        .HasColumnName("volume");

                    b.HasKey("ObjectId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("object_materials");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.CalculationMethod", b =>
                {
                    b.Property<int>("IdCalculationMethod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_calculation_method");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCalculationMethod"));

                    b.Property<string>("AssignedObjects")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assigned_objects");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("IdCalculationMethod");

                    b.ToTable("calculation_methods");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.DamageEvaluation", b =>
                {
                    b.Property<int>("IdDamageEvaluation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_damage_evaluation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDamageEvaluation"));

                    b.Property<int?>("CalculationMethodId")
                        .HasColumnType("integer")
                        .HasColumnName("fk_calculation_method");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("fk_event");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<double?>("PiniginisDydis")
                        .HasColumnType("double precision")
                        .HasColumnName("piniginis_dydis");

                    b.Property<double?>("ZalosDydis")
                        .HasColumnType("double precision")
                        .HasColumnName("zalos_dydis");

                    b.HasKey("IdDamageEvaluation");

                    b.HasIndex("CalculationMethodId");

                    b.HasIndex("EventId");

                    b.ToTable("damage_evaluations");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.EnvironmentObject", b =>
                {
                    b.Property<int>("IdObject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_object");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdObject"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("IdObject");

                    b.ToTable("objects");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.Event", b =>
                {
                    b.Property<int>("IdEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_event");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEvent"));

                    b.Property<Polygon>("Coordinates")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("coordinates");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EventDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdEvent");

                    b.ToTable("events");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.EventObject", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<int>("ObjectId")
                        .HasColumnType("integer")
                        .HasColumnName("object_id");

                    b.HasKey("EventId", "ObjectId");

                    b.HasIndex("ObjectId");

                    b.ToTable("event_objects");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.Fraction", b =>
                {
                    b.Property<int>("IdFraction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_fraction");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFraction"));

                    b.Property<int>("ComponentMaterialId")
                        .HasColumnType("integer")
                        .HasColumnName("component_material_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("Mass")
                        .HasColumnType("double precision")
                        .HasColumnName("mass");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer")
                        .HasColumnName("fk_material_id_material");

                    b.Property<double?>("Percentage")
                        .HasColumnType("double precision")
                        .HasColumnName("percentage");

                    b.Property<double?>("Volume")
                        .HasColumnType("double precision")
                        .HasColumnName("volume");

                    b.HasKey("IdFraction");

                    b.HasIndex("ComponentMaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("fractions");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.IncidentMaterial", b =>
                {
                    b.Property<int>("IdIncidentMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_incident_material");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdIncidentMaterial"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("id_event");

                    b.Property<double?>("Mass")
                        .HasColumnType("double precision")
                        .HasColumnName("mass");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer")
                        .HasColumnName("id_material");

                    b.Property<double?>("Percentage")
                        .HasColumnType("double precision")
                        .HasColumnName("percentage");

                    b.Property<double?>("Volume")
                        .HasColumnType("double precision")
                        .HasColumnName("volume");

                    b.HasKey("IdIncidentMaterial");

                    b.HasIndex("EventId");

                    b.HasIndex("MaterialId");

                    b.ToTable("incident_materials");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.Map", b =>
                {
                    b.Property<int>("IdMap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_map");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMap"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("geometry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("IdMap");

                    b.ToTable("maps");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.MapMaterial", b =>
                {
                    b.Property<int>("MapId")
                        .HasColumnType("integer")
                        .HasColumnName("id_map");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer")
                        .HasColumnName("id_material");

                    b.HasKey("MapId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("map_materials");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.Material", b =>
                {
                    b.Property<int>("IdMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_material");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMaterial"));

                    b.Property<decimal>("BaseRate")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("HarmfulnessFactor")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<double?>("ToxicityFactor")
                        .HasColumnType("double precision")
                        .HasColumnName("toxicity_factor");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.HasKey("IdMaterial");

                    b.ToTable("materials");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.Specialist", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<string>("FieldOfExpertise")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("field_of_expertise");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("IdUser");

                    b.ToTable("specialists");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.HasKey("IdUser");

                    b.ToTable("users");
                });

            modelBuilder.Entity("ObjectMaterial", b =>
                {
                    b.HasOne("ŽVPAIS_API.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ŽVPAIS_API.Models.EnvironmentObject", "EnvironmentObject")
                        .WithMany("ObjectMaterials")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnvironmentObject");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.DamageEvaluation", b =>
                {
                    b.HasOne("ŽVPAIS_API.Models.CalculationMethod", "CalculationMethod")
                        .WithMany("DamageEvaluations")
                        .HasForeignKey("CalculationMethodId");

                    b.HasOne("ŽVPAIS_API.Models.Event", "Event")
                        .WithMany("DamageEvaluations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalculationMethod");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.EventObject", b =>
                {
                    b.HasOne("ŽVPAIS_API.Models.Event", "Event")
                        .WithMany("EventObjects")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ŽVPAIS_API.Models.EnvironmentObject", "Object")
                        .WithMany("EventObjects")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.Fraction", b =>
                {
                    b.HasOne("ŽVPAIS_API.Models.Material", "ComponentMaterial")
                        .WithMany("ComponentFractions")
                        .HasForeignKey("ComponentMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ŽVPAIS_API.Models.Material", "Material")
                        .WithMany("Fractions")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ComponentMaterial");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.IncidentMaterial", b =>
                {
                    b.HasOne("ŽVPAIS_API.Models.Event", "Event")
                        .WithMany("IncidentMaterials")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ŽVPAIS_API.Models.Material", "Material")
                        .WithMany("IncidentMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.MapMaterial", b =>
                {
                    b.HasOne("ŽVPAIS_API.Models.Map", "Map")
                        .WithMany("MapMaterials")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ŽVPAIS_API.Models.Material", "Material")
                        .WithMany("MapMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.Specialist", b =>
                {
                    b.HasOne("ŽVPAIS_API.Models.User", "User")
                        .WithOne("Specialist")
                        .HasForeignKey("ŽVPAIS_API.Models.Specialist", "IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.CalculationMethod", b =>
                {
                    b.Navigation("DamageEvaluations");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.EnvironmentObject", b =>
                {
                    b.Navigation("EventObjects");

                    b.Navigation("ObjectMaterials");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.Event", b =>
                {
                    b.Navigation("DamageEvaluations");

                    b.Navigation("EventObjects");

                    b.Navigation("IncidentMaterials");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.Map", b =>
                {
                    b.Navigation("MapMaterials");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.Material", b =>
                {
                    b.Navigation("ComponentFractions");

                    b.Navigation("Fractions");

                    b.Navigation("IncidentMaterials");

                    b.Navigation("MapMaterials");
                });

            modelBuilder.Entity("ŽVPAIS_API.Models.User", b =>
                {
                    b.Navigation("Specialist")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
